import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0A0A0A",
        foreground: "#FFFFFF",
        "foreground-muted": "#E0E0E0",
        primary: "#1A1A1A",
        "primary-button": "#F0F0F0",
        "primary-button-foreground": "#1A1A1A",
        "secondary-button": "#333333",
        muted: "#71717A",
        accent: "#B0B0B0",
        "accent-dark": "#A0A0A0",
        "banner-bg": "#2C2C2C",
        "dashboard-bg": "#0a0a0c",
        "dashboard-card": "#282828",
        "dashboard-title": "#C0C0C0",
        "tab-active-bg": "#D0D0D0",
        "tab-active-text": "#1A1A1A",
        "chart-bar": "#3A3A3A",
        brand: "#FB923C",
        "brand-foreground": "#FDBA74",
        cta: "#FF6B3E",
        positive: "#4CAF50",
        border: "rgba(250, 250, 250, 0.1)",
        cream: "#EFF4FF",
        neon: "#6FFF00",
        "careers-primary": "#DEDBC8",
        "careers-text": "#E1E0CC",
        "careers-card": "#101010",
        "careers-feature": "#212121",
        swiss: {
          bg: "#FFFFFF",
          fg: "#000000",
          muted: "#F2F2F2",
          accent: "#FF3000",
        },
        ei: {
          forest: "#1A3C2E",
          lime: "#8CC63F",
          cream: "#F9FAF5",
          nav: "#8CC63F",
          primaryDark: "#143326",
          primary: "#1A3C2E",
          teal: "#2D6B52",
          secondary: "#5A9E6F",
          accent: "#8CC63F",
          action: "#8CC63F",
          background: "#F9FAF5",
          surface: "#FFFFFF",
          textPrimary: "#1A3C2E",
          muted: "#4A6358",
        },
        rb: {
          navy: "#0D2847",
          brand: "#2B79C2",
          sky: "#6BB4F0",
          cream: "#F5F9FC",
          nav: "#2B79C2",
          primaryDark: "#1A4A75",
          primary: "#2B79C2",
          deep: "#1E5A9C",
          secondary: "#4A9AD4",
          accent: "#6BB4F0",
          action: "#2B79C2",
          background: "#F5F9FC",
          surface: "#FFFFFF",
          textPrimary: "#0D2847",
          muted: "#4A6280",
        },
      },
      backgroundImage: {
        "ei-brand-gradient": "linear-gradient(180deg, #B4DE63 0%, #0F5C4F 100%)",
        "ei-feature-gradient": "linear-gradient(135deg, #84AF55 0%, #56C596 45%, #0F5C4F 100%)",
      },
      fontSize: {
        "hero": ["3.25rem", { lineHeight: "1.15" }],
        "hero-lg": ["3.75rem", { lineHeight: "1.15" }],
      },
      borderRadius: {
        "dashboard": "1rem",
      },
      boxShadow: {
        "dashboard": "0 28px 56px -14px rgba(0, 0, 0, 0.55), 0 14px 32px -10px rgba(0, 0, 0, 0.45), 0 4px 12px -4px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255,255,255,0.04)",
      },
      fontFamily: {
        sans: ["Poppins", "ui-sans-serif", "system-ui", "sans-serif"],
        "ei-heading": ["var(--font-ei-heading)", "ui-sans-serif", "system-ui", "sans-serif"],
        "ei-body": ["var(--font-ei-body)", "ui-sans-serif", "system-ui", "sans-serif"],
        "rb-heading": ["var(--font-rb-heading)", "ui-sans-serif", "system-ui", "sans-serif"],
        "rb-body": ["var(--font-rb-body)", "ui-sans-serif", "system-ui", "sans-serif"],
        grotesk: ["Anton", "ui-sans-serif", "system-ui", "sans-serif"],
        condiment: ["Condiment", "cursive"],
        almarai: ["Almarai", "ui-sans-serif", "system-ui", "sans-serif"],
        "instrument-serif": ['"Instrument Serif"', "serif"],
        inter: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      maxWidth: {
        container: "1312px",
        "container-sm": "720px",
      },
      keyframes: {
        "dashboard-enter": {
          "0%": { opacity: "0", transform: "translateY(24px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "card-enter": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "bar-grow": {
          "0%": { transform: "scaleY(0)", transformOrigin: "bottom" },
          "100%": { transform: "scaleY(1)", transformOrigin: "bottom" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "ei-phone-enter": {
          "0%": { opacity: "0", transform: "translateY(24px) scale(0.96)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
        "canvas-fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "globe-spin": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "dashboard-enter": "dashboard-enter 0.6s ease-out forwards",
        "card-enter": "card-enter 0.5s ease-out forwards",
        "bar-grow": "bar-grow 0.6s ease-out forwards",
        "fade-in": "fade-in 0.4s ease-out forwards",
        "ei-phone-enter": "ei-phone-enter 0.8s cubic-bezier(0.22, 1, 0.36, 1) forwards",
        "canvas-fade-in": "canvas-fade-in 0.8s ease-out forwards",
        "globe-spin": "globe-spin 24s linear infinite",
      },
      transitionDuration: {
        200: "200ms",
        300: "300ms",
      },
    },
  },
  plugins: [],
};

export default config;
